// This is some example data to use.
// Feel free to modify this to make sense with the game system you're using.
var dynamic_sheet_attrs = {
  "name" : "Harrison Scully",
  "player" : "<a href='http://www.obsidianportal.com/profile/dorward'>dorward</a>",
  "campaign" : "<a href='http://www.obsidianportal.com/campaigns/jago-and-litefoot'>Victoriana</a>",
  "rank": 1,
  "nationality": "British",
  "childhood": "Urchin",
  "social_class": "Lower",
  "age": "21",
  "gender": "Male",
  "vocation": "Soldier",
  "race": "Human",
  "build": "Medium",
  "personality": "Optimist",
  "hair": "Brown",
  "eyes": "Brown",
  "ethics": "Lower class",

  "str": 2,
  "dex": 2,
  "fort": 2,
  "pres": 2,
  "wits": 2,
  "res": 1,

  "common_skill_act" : 0,
  "common_skill_athletics" : 0,
  "common_skill_blunt" : 0,
  "common_skill_bull" : 0,
  "common_skill_charm" : 0,
  "common_skill_conceal" : 0,
  "common_skill_concentration" : 0,
  "common_skill_dance" : 0,
  "common_skill_dodge" : 0,
  "common_skill_drive" : 0,
  "common_skill_empathy" : 0,
  "common_skill_etiquette" : 0,
  "common_skill_firearms" : 0,
  "common_skill_fisticuffs" : 0,
  "common_skill_general" : 0,
  "common_skill_hide" : 0,
  "common_skill_horse" : 0,
  "common_skill_improvised" : 0,
  "common_skill_intimidate" : 0,
  "common_skill_might" : 0,
  "common_skill_perception" : 0,
  "common_skill_streetwise" : 0,
  "common_skill_swordplay" : 0,
  "common_skill_throwing" : 0
};